--- #YAML:1.0
name:               Synapse-MailSender
version:            1.3
abstract:           ~
author:  []
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    MIME::Lite:           0
    MIME::Type::FileName:  0
    Petal::Tiny:          0
    XML::Parser::REX:     0
    YAML::XS:             0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
